
var tool = {
    api:'http://xxxxxx/',
    ws:'ws://xxxxx/ws',
    getQueryVariable:function(variable){
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i=0;i<vars.length;i++) {
            var pair = vars[i].split("=");
            if(pair[0] == variable){return pair[1];}
        }
        return(false);
    },
    ChartjsRandColor:function(){
        var colorArr = [
            '#FFEFD5',
            '#FFEC8B',
            '#FFEBCD',
            '#FFE7BA',
            '#FFE4E1',
            '#FFE4C4',
            '#FFE4B5',
            '#FFE1FF',
            '#FFDEAD',
            '#FFDAB9',
            '#FFD700',
            '#FFD39B',
            '#FFC1C1',
            '#FFC125',
            '#FFC0CB',
            '#FFBBFF',
            '#FFB90F',
            '#FFB6C1',
            '#FFB5C5',
            '#FFAEB9',
            '#FFA54F',
            '#FFA500',
            '#FFA07A',
            '#FF8C69',
            '#FF8C00',
            '#FF83FA',
            '#FF82AB',
            '#FF8247',
            '#FF7F50',
            '#FF7F24',
            '#FF7F00',
            '#FF7256',
            '#FF6EB4',
            '#FF6A6A',
            '#FF69B4',
            '#FF6347',
            '#EEE8AA',
            '#EEE685',
            '#EEE5DE',
            '#EEE0E5',
            '#EEDFCC',
            '#EEDC82',
            '#EED8AE',
            '#EED5D2',
            '#EED5B7',
            '#EED2EE',
            '#EECFA1',
            '#EECBAD',
            '#EEC900',
            '#EEC591',
            '#EEB4B4',
            '#EEB422',
            '#EEAEEE',
            '#EEAD0E',
            '#EEA9B8',
            '#EEA2AD',
            '#EE9A49',
            '#EE9A00',
            '#EE9572',
            '#EE82EE',
            '#EE8262',
            '#EE7AE9',
            '#EE799F',
            '#EE7942',
            '#EE7621',
            '#EE7600',
            '#EE6AA7',
            '#EE6A50',
            '#269cef',
            '#1b98b7',
            '#895be8',
            '#2967d9',
            '#5e53c6',
            '#1163dd',
            '#00b1d1',
            '#0062be',
            '#497ed6',
            '#7a63f2',
            '#ff6e51',
            '#e55b40',
            '#ea3d1b',
            '#f44538',
            '#ed5012',
            '#ec363e',
            '#ec365c',
            '#d7163f',
            '#e1357a',
            '#c43794',
            '#e74ac8',
            '#25d2d4',
            '#25d4b5',
            '#25d48c',
            '#25d453',
            '#25d42e',
            '#7fc563',
            '#47bc9f',
            '#22be6c',
            '#50ba5c',
            '#6dc327',
        ];
        var min = 0;
        var max = (colorArr.length-1);
        var randNum = Math.floor(Math.random()*(max-min))+min;
        return colorArr[randNum];
    }
};